#!/bin/bash
cat zoo/nick
cat zoo/Eric


cat zoo/steven_ahl
cat zoo/evan

cat zoo/daniel.hanle
cat zoo/michael

cat zoo/daniel.hanlen
cat zpp/MatthewHarris
cat zoo/devlyntobin

cat zoo/jacqueline.wilkes
cat zoo/anna
