#!/bin/bash -e


echo my name is Julio Vergara, going for computer science 
echo
echo My name is Daniel Hanlen, I work making medical software, and graduate soon with a BS in Computer Science.
echo
echo
echo
echo
echo my name is devlyn tobin i am computer science and chemical engineering major.
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo Tests complete
echo You should write more tests
