#!/bin/bash -e


echo My Name is Sandra Mondragon,I am a transfer student from Columbia Basin
echo College,
echo 
echo I plan to graduate next year with a BS in Computer Science
echo I am a first generation college student in my family
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
#~/. bash rc
