#!/bin/bash -e


echo My Name is Evan Felix, I am the instructor for the class and Graduated from Utah State University.
echo
echo my name is Julio Vergara, going for computer science 
echo
echo My name is Daniel Hanlen, I work making medical software, and graduate soon with a BS in Computer Science.
echo
echo My name is Steven Ahl.  I am a trophy husband and working on my BA in Comp Sci
echo
echo My name is Rebecca Hoerner. I'm working towards a BA in Computer Science.
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo Tests complete
echo You should write more tests
